version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
kubejs = true
fastitemframes = true
farmersdelight = true
factory_blocks = true
fireflybush = true
create_factory_logistics = true
create = true
ribbits = true
etched = true
uppers = true
visualworkbench = true
minecraft = true
create_connected = true
create_dragons_plus = true
lootr = true
unusual_furniture = true
create_enchantment_industry = true
trading_floor = true
travelersbackpack = true
fastpaintings = true
minted = true
createframed = true
create_mobile_packages = true
createmechanisms = true
amendments = true
ftbquests = true
vanillabackport = true
chisel = true
exposure = true
create_power_loader = true
